spring:
  application:
    name: JournalApplication
  port: 8080

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    ssl:
      enabled: true
      timeout: 3000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  logging:
    level:
      org:
        mongodb:
          driver: DEBUG

logging:
  level:
    com:
      SpringBootProject:
        journalApp: TRACE

weather:
  api:
    key: ${WEATHER_API_KEY}
