### Application Name
##spring.application.name=JournalApplication
##
### MongoDB Connection
##spring.data.mongodb.uri=mongodb+srv://Rohan:Rohan%402003@cluster0.nikdi.mongodb.net/myjournaluser?retryWrites=true&w=majority&tls=true&connectTimeoutMS=60000
##
### Enable Auto Index Creation
##spring.data.mongodb.auto-index-creation=true
##x-creation=true
##logging.level.org.mongodb.driver=DEBUG
#
#
spring:
  .application:
    .name: JournalApplication
  .data:
    .mongodb:
      .uri : mongodb+srv://Rohan:Rohan%402003@cluster0.nikdi.mongodb.net/myjournaluser?retryWrites=true&w=majority&tls=true&connectTimeoutMS=60000
      .auto-index-creation : true
  redis:
    host: redis-17377.crce182.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 17377
    username: default
    password: 98M6NpJXBf3wN5KERbRtBi3wguITsIAG
    ssl:
      enabled: true
      timeout: 3000
  mail:
    host: smtp.gmail.com
    port: 587
    username: rohankrote2003@gmail.com
    password: ydlu lhak pmxf wgof
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

x-creation: true
logging:
  level:
    org:
      mongodb:
        driver: DEBUG

